repos:
    - repo: local
      hooks:
          - id: formatter
            name: Spotless
            entry: bash ./scripts/pre-commit-formatter
            language: system
            verbose: true
